/**
 * @file constantes.hpp
 * @author DELARUELLE DEPEYRIS
 * @brief Définition des constantes du jeu
 * @version 0.1
 * @date 2025-01-18
 * 
 * @copyright Copyright (c) 2025
 * 
 */

#ifndef constantes_hpp
#define constantes_hpp

#define NB_CASES 40
#define NB_JOUEURS_MAX 8
#define NB_JOUEURS_MIN 2
#define NB_HOTELS 12
#define NB_MAISONS 32
#define AMANDE_PRISON 50
#define MAX_TOUR_PRISON 3

enum class cartesChance {
    AVANCER_CASE_DEPART,
    RDV_RUE_LA_PAIX,
    RDV_HENRI_MARTIN,
    REPARATION_MAISON_4000_HOTEL_11500,
    AVANCER_GARE_DE_LYON,
    PRIX_MOTS_CROISES,
    DIVIDENDE_BANCAIRE,
    LIBERE_PRISON,
    RECULER_3_CASES,
    ALLER_PRISON,
    REPARATION_MAISON_2500_HOTEL_10000,
    AMENDE_EXCES_VITESSE,
    PAYEZ_FRAIS_SCOLARITE,
    AMENDE_IVRESSE,
    IMMEUBLE_PRET_RAPPORTENT,
    RDV_BLVD_VILLETTE
} ;

enum class cartesCommunaute {
    PLACEZ_VOUS_CASE_DEPART,
    ERREUR_BANQUE,
    NOTE_DOCTEUR,
    VENTE_STOCK,
    LIBERE_PRISON,
    ALLER_PRISON,
    RETOURNEZ_BELLEVILLE,
    REVENU_ANNUEL,
    ANNIVERSAIRE,
    CONTRIBUTIONS_REMBOURSENT,
    INTERETS_PRET,
    POLICE_ASSURANCE,
    AMENDE_OU_CARTE_CHANCE,
    RDV_GARE_LA_PLUS_PROCHE,
    PRIX_DE_BEAUTE,
    HERITAGE
} ;

#endif